### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by thrayam** [shivsingh7150/whmcs-Instamojo-payment-gateway#1]
Hello Shiv,

I try to install this modules, after adding this module the Payment Gateway page is not loading, please check

i'm using WHMCS 6.3.1

Thanks
Anu

**Comment by ProgrammerNomad** [comment]
Hello Anu,
Can please clear what is issue, page is showing black or anything else? please provide screenshot if possible,

And you can try this latest version: http://www.kmwebsoft.com/free-zone/WHMCS-Instamjo-Plugin.zip

Thanks

**Comment by big89** [comment]
Hello All,

If any one wants to discuss on this, contact me. I will help regarding this development.

**Comment by ProgrammerNomad** [comment]
too old and no one responding so closing now
