### ISSUE TITLE
Getting errors while checking out

### ISSUE THREAD

**Issue by tdram** [shivsingh7150/whmcs-Instamojo-payment-gateway#2]
Hi,

I have WHMCS version 6.3.1 and I have installed your module . But while checking out, it throws the error.

Error: {"purpose":["Ensure this field has no more than 30 characters."]}
Error: {"purpose":["This field is required."],"amount":["This field is required."]}

and it doesn't go to payment gateway and not works.

How to overcome this issue? Also, the jquery.js file which you have mentioned in  whmcs-Instamojo-payment-gateway/upload-it/modules/gateways/instamojo/RequestHandler.php

line 60 `<script src="https://www.example.com/template/js/jquery.js"></script>`

shows 404 page.

**Comment by big89** [comment]
Hi,

If you want to use instamojo payment gateway in WHMCS, we can help you professionally for that.
You can consult with us for this implementation.

Thanks,
Bhagwan

**Comment by tdram** [comment]
Hi,

Our PHP dev fixed the error. Thank you for the plugin :)
